/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'background': '#faf8ff',
        'surface': '#faf8ff',
        'surface-dim': '#d9d9e5',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3fe',
        'surface-container': '#ededf9',
        'surface-container-high': '#e7e7f3',
        'surface-container-highest': '#e1e2ed',
        'on-surface': '#191b23',
        'on-surface-variant': '#434655',
        'on-background': '#191b23',
        'inverse-surface': '#2e3039',
        'inverse-on-surface': '#f0f0fb',
        'outline': '#737686',
        'outline-variant': '#c3c6d7',
        'surface-tint': '#0053db',
        'surface-variant': '#e1e2ed',
        'primary': '#004ac6',
        'on-primary': '#ffffff',
        'primary-container': '#2563eb',
        'on-primary-container': '#eeefff',
        'inverse-primary': '#b4c5ff',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'secondary': '#515f74',
        'on-secondary': '#ffffff',
        'secondary-container': '#d5e3fc',
        'on-secondary-container': '#57657a',
        'secondary-fixed': '#d5e3fc',
        'secondary-fixed-dim': '#b9c7df',
        'on-secondary-fixed': '#0d1c2e',
        'on-secondary-fixed-variant': '#3a485b',
        'tertiary': '#943700',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#bc4800',
        'on-tertiary-container': '#ffede6',
        'tertiary-fixed': '#ffdbcd',
        'tertiary-fixed-dim': '#ffb596',
        'on-tertiary-fixed': '#360f00',
        'on-tertiary-fixed-variant': '#7d2d00',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        // Simplified aliases
        'workflow-bg': '#faf8ff',
        'workflow-surface': '#ffffff',
        'workflow-surface-subtle': '#f3f3fe',
        'workflow-surface-muted': '#ededf9',
        'workflow-text': '#191b23',
        'workflow-muted': '#434655',
        'workflow-border': '#c3c6d7',
        'workflow-primary': '#004ac6',
        'workflow-primary-strong': '#003ea8',
        'workflow-secondary': '#515f74',
        'workflow-danger': '#ba1a1a',
        'workflow-success': '#087443',
        'workflow-warning': '#9a5b13',
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      boxShadow: {
        soft: '0 10px 15px -3px rgba(0, 0, 0, 0.05)',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      spacing: {
        'gutter': '1.5rem',
        'container-max': '1280px',
        18: '4.5rem',
        22: '5.5rem',
      },
    },
  },
}